use_frameworks!

platform :ios, '10.0'

target 'verticalityAdBanner_Example' do
  pod 'verticalityAdBanner', :path => '../'

  target 'verticalityAdBanner_Tests' do
    inherit! :search_paths

    
  end
end
